import os
import io
import pandas as pd
from flask import Blueprint, send_file, current_app
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from database import get_db
from auth_utils import require_auth

export_bp = Blueprint("export", __name__)

@export_bp.route("/<upload_id>", methods=["GET"])
@require_auth
def export_dataset(upload_id):
    # require_auth stores user_id in request.current_user_id
    from flask import request
    user_id = getattr(request, "current_user_id", None)
    
    supabase = get_db()
    
    # 1. Get upload details
    res = supabase.table("uploads").select("*").eq("id", upload_id).eq("user_id", user_id).single().execute()
    if not res.data:
        return {"error": "Dataset not found"}, 404
    
    upload = res.data
    file_path = upload.get("file_path")
    
    if not file_path or not os.path.exists(file_path):
        return {"error": "Raw data file missing on server"}, 404

    # 2. Read data
    try:
        if file_path.endswith(".csv"):
            df = pd.read_csv(file_path)
        else:
            df = pd.read_excel(file_path)
    except Exception as e:
        return {"error": f"Failed to read data: {str(e)}"}, 500

    # 3. Create PDF in memory
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=20,
        textColor=colors.HexColor("#6366f1")
    )
    elements.append(Paragraph(f"Data Summary: {upload['filename']}", title_style))
    elements.append(Paragraph(f"Generated on: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Stats Summary
    elements.append(Paragraph("Dataset Overview", styles['Heading2']))
    stats_data = [
        ["Total Rows", str(len(df))],
        ["Total Columns", str(len(df.columns))],
        ["File Size", f"{os.path.getsize(file_path) / 1024:.1f} KB"]
    ]
    t = Table(stats_data, colWidths=[150, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 6)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # Column Details
    elements.append(Paragraph("Column Schema", styles['Heading2']))
    schema_data = [["Column Name", "Data Type", "Non-Null Count"]]
    for col in df.columns:
        schema_data.append([col, str(df[col].dtype), str(df[col].count())])
    
    st = Table(schema_data, colWidths=[200, 100, 150])
    st.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#6366f1")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('FONTSIZE', (0,0), (-1,0), 12),
        ('BOTTOMPADDING', (0,0), (-1,0), 12),
    ]))
    elements.append(st)
    elements.append(Spacer(1, 20))

    # Footer
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("Generated by InsightlyAI — Advanced Sales Intelligence", styles['Italic']))

    # Build PDF
    doc.build(elements)
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"Report_{upload['filename']}.pdf",
        mimetype='application/pdf'
    )
